FROM golang

#RUN apk update
#RUN apk add git
RUN go get github.com/derekparker/delve/cmd/dlv
RUN mkdir -p $GOPATH/src/server
ADD ./tcp_server.go $GOPATH/src/server/
WORKDIR $GOPATH/src/server/

RUN go build -gcflags='-N -l' -o server tcp_server.go